[[redirects]]
  from = "/api"
  to = "https://date.nager.at/api/v2/"
  status = 200
  force = true
  [headers.values]
      Access-Control-Allow-Origin = "*"
      X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200